## Linear Regression: Practice Session 1

In [2]:
import torch 
import numpy as np

**Practice Session 1:**

+ Building linear regression for 1D
+ Building linear regression for 2D
+ Apply gradient descent

## Linear Regression 1D

### Linear Regression

In [3]:
# construct a linear regression model 
w = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(4.0, requires_grad=True)

def forward(x, w, b):
  ypred = x*w + b
  return ypred

# compute the prediction for given value of x
x = torch.tensor(-5.0, requires_grad=True)
ypred = forward(x, w, b)
print(f"Predicted value of x: {ypred}")

Predicted value of x: -11.0


In [10]:
# compute 5 list of predicted values
input_x = np.float32([2,-1,5,2,6])
input_vals = torch.tensor(input_x, requires_grad=True)
predicted_vals = []

for i, x in enumerate(input_vals): 
  ypred = forward(x, w, b)
  predicted_vals.append((i, ypred))
  print(f"Predicted Value {i}: {ypred}")

epochs = [i[0] for i in predicted_vals]
ypreds = [i[1] for i in predicted_vals]
print(f"Epochs: {epochs}")
print(f"Y predictions: {ypreds}")

Predicted Value 0: 10.0
Predicted Value 1: 1.0
Predicted Value 2: 19.0
Predicted Value 3: 10.0
Predicted Value 4: 22.0
Epochs: [0, 1, 2, 3, 4]
Y predictions: [tensor(10., grad_fn=<AddBackward0>), tensor(1., grad_fn=<AddBackward0>), tensor(19., grad_fn=<AddBackward0>), tensor(10., grad_fn=<AddBackward0>), tensor(22., grad_fn=<AddBackward0>)]


In [9]:
predicted_vals
epochs

[0, 1, 2, 3, 4]

### Class Linear

In [24]:
from torch.nn import Linear
import torch.nn as nn 

In [16]:
torch.manual_seed(1)

In [17]:
# create 1D x value for y prediction computation
x = torch.tensor([-2.0], requires_grad=True)

# build a linear regression model from pytorch
model = Linear(in_features=1, out_features=1)
y = model(x)
print(f"y predicted value: {y}")

y predicted value: tensor([-1.4719], grad_fn=<ViewBackward0>)


In [21]:
w, b = list(model.parameters())
print(f"parameter w: {w}")
print(f"parameter b: {b}")

parameter w: Parameter containing:
tensor([[0.5153]], requires_grad=True)
parameter b: Parameter containing:
tensor([-0.4414], requires_grad=True)


In [25]:
class LRmodel(nn.Module):
  def __init__(self, in_size, out_size): 
    super(LRmodel, self).__init__()
    self.linear = nn.Linear(in_size, out_size)

  def forward(self, x): 
    output = self.linear(x)
    return output

In [29]:
# x1 =  torch.tensor([5.0])
# x2 = torch.tensor([-3.0])

lin_model = LRmodel(in_size=1, out_size=1)
# lin_model.forward(-2.0)

In [35]:
w = lin_model.state_dict()["linear.weight"]
b = lin_model.state_dict()["linear.bias"]
(f"w: {w}", f"b: {b}")

('w: tensor([[0.0479]])', 'b: tensor([0.5961])')

In [39]:
lin_model.state_dict()["linear.weight"].data[0] = torch.tensor([[0.01254]])
w

tensor([[0.0125]])

In [42]:
list(lin_model.parameters())

[Parameter containing:
 tensor([[0.0125]], requires_grad=True),
 Parameter containing:
 tensor([0.5961], requires_grad=True)]

## Linear Regression: 2D

In [46]:
# create 2d constants to compute linear regression
x1 = np.array([[1,2,3,5],[5,2,1,4]], dtype=float)
x2 = np.array([[1,5,2,4],[5,2,1,7]], dtype=float)
xvector1 = torch.tensor(x1, requires_grad=True)
xvector2 = torch.tensor(x2, requires_grad=True)



tensor([[1., 2., 3., 5.],
        [5., 2., 1., 4.]], dtype=torch.float64, requires_grad=True)